### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#55]
### Descrição:
Técnica utilizada para confirmar o que foi feito e quais pontos anda estão com dependência. Pode ser usada em vários contextos

### Critérios de Aceitação
- [ ] Checklist aplicado 
- [ ] Documento na wiki

### Tarefas
- [ ] Analisar onde pode ser utilizado o checklist
- [ ] Documentar o checklist
- [ ] Passar pelo checklist junto com a equipe com a finalidade de evitar erros

**Comment by arthurbdiniz** [comment]
Sobre esse checklist é para montar apenas o script dos documentos que vamos fazer o checklist, o checklist vai ser feito dia 13 quinta-feira com todos os integrantes

**Comment by RomeuCarvalhoAntunes** [comment]
Criei um modelo inicial do checklist onde irá ser finalizado na reunião de hoje, juntamente com um processo de validação para a "primeira entrega" dia (14/09/2018)
